# Generated by Django 4.1.7 on 2023-04-01 19:47

from django.db import migrations, models

import core.services.upload_car_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.upload_car_service.upload_to),
        ),
    ]
