# Generated by Django 4.1.7 on 2023-03-28 09:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z]{2,50}$', 'min 2 max 50')])),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2022)])),
                ('price', models.IntegerField(default=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_parks.autoparksmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
