# Generated by Django 4.1.7 on 2023-04-01 19:47

from django.db import migrations, models

import core.services.upload_avatar_service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.services.upload_avatar_service.upload_to),
        ),
    ]
