# Generated by Django 4.1.7 on 2023-03-29 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])([^\\s]){8,16}$', ['password must contain 1 number(0-9)', 'password must contain 1 uppercase letter', 'password must contain 1 lowercase letter', 'password must contain 1 non-alpha numeric number', 'password is 5-16 characters with no space'])]),
        ),
    ]
