# Generated by Django 4.1.7 on 2023-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=25),
        ),
    ]
